// Mock 数据集中管理 — 智能采集工作台
import type { TemplateAsset, CollectTask } from './types';

export const templates: TemplateAsset[] = [
  {
    key: '1',
    name: 'google_patent_contract',
    title: 'Google Patent Contract',
    domain: 'patents.google.com',
    adapter: 'browser-agent',
    version: 'v1.8',
    status: 'active',
    fields: 18,
    quality: 94,
    lastRun: '8 分钟前',
    owner: 'AI Collect',
    description: '沉淀专利列表、详情页、附件与翻页路径，支持字段漂移检测和增量同步。',
    action: '打开模板',
    icon: 'cloud',
    taskCount: 3,
  },
  {
    key: '2',
    name: 'sealagom_navwarn_contract',
    title: 'Navwarn Sync Template',
    domain: 'navigation warning',
    adapter: 'http-parser',
    version: 'v2.1',
    status: 'active',
    fields: 12,
    quality: 98,
    lastRun: '16 分钟前',
    owner: 'Crawler Team',
    description: '面向航警数据的稳定采集模板，内置区域编码、重复合并和低延迟入湖策略。',
    action: '查看运行',
    icon: 'api',
    taskCount: 1,
  },
  {
    key: '3',
    name: 'zdopen_notice_contract',
    title: 'Gov Notice Template',
    domain: '政务公告',
    adapter: 'browser-render',
    version: 'v0.9',
    status: 'draft',
    fields: 15,
    quality: 76,
    lastRun: '1 小时前',
    owner: 'Data Ops',
    description: '用于公告列表和详情页还原，当前处于草稿验证阶段，等待验证码风险策略确认。',
    action: '继续调试',
    icon: 'tool',
    taskCount: 1,
  },
  {
    key: '4',
    name: 'pdf_document_extract',
    title: 'PDF Extract Template',
    domain: 'PDF 附件',
    adapter: 'doc-parser',
    version: 'v1.3',
    status: 'active',
    fields: 9,
    quality: 91,
    lastRun: '32 分钟前',
    owner: 'ETL Team',
    description: '专门处理附件下载、文本抽取、对象存储归档和结构化字段回填。',
    action: '试跑模板',
    icon: 'search',
    taskCount: 1,
  },
  {
    key: '5',
    name: 'quality_missing_scan',
    title: 'Quality Gate Template',
    domain: '质量校验',
    adapter: 'quality-agent',
    version: 'v1.1',
    status: 'draft',
    fields: 7,
    quality: 88,
    lastRun: '47 分钟前',
    owner: 'Data Ops',
    description: '集中维护字段缺失率、重复记录、字段漂移和发布门禁，供任务发布前复用。',
    action: '配置门禁',
    icon: 'branch',
    taskCount: 1,
  },
  {
    key: '6',
    name: 'legacy_notice_parser',
    title: 'Legacy Notice Parser',
    domain: '历史公告',
    adapter: 'legacy-parser',
    version: 'v0.6',
    status: 'deprecated',
    fields: 11,
    quality: 63,
    lastRun: '7 天前',
    owner: 'Crawler Team',
    description: '旧版解析器模板，仅保留回滚和历史任务兼容，不建议新任务继续引用。',
    action: '查看归档',
    icon: 'code',
    taskCount: 0,
  },
];

export const tasks: CollectTask[] = [
  {
    key: '1',
    name: 'Google Patent daily sync',
    template: 'google_patent_contract@v1.8',
    group: 'prototype',
    area: 'Patents 🧭',
    status: 'completed',
    progress: 85,
    records: '18.2K',
    lag: '42s',
    nextRun: '持续运行',
    owner: 'lucid-jellybean',
    avatar: 'LJ',
    comments: ['页面结构稳定，列表与详情链路已进入持续同步。', '附件下载成功率 98.7%，失败样本进入补偿队列。'],
    subIssues: [
      { title: '详情页 canonical URL 校验', status: 'completed', id: '#1752' },
      { title: 'PDF 附件断点续采', status: 'running', id: '#1753' },
      { title: '字段漂移基线固化', status: 'queued', id: '#1754' },
    ],
  },
  {
    key: '2',
    name: 'Sealagom navwarn sync',
    template: 'sealagom_navwarn_contract@v2.1',
    group: 'prototype',
    area: 'Navwarn 🌊',
    status: 'running',
    progress: 54,
    records: '4.6K',
    lag: '18s',
    nextRun: '持续运行',
    owner: 'aiden-garcia',
    avatar: 'AG',
    comments: ['Socket 正在推送批次进度，最近 10 分钟无失败记录。'],
    subIssues: [
      { title: '区域编码映射', status: 'running', id: '#1761' },
      { title: '增量窗口缩短到 10 分钟', status: 'queued', id: '#1762' },
      { title: '重复航警合并', status: 'completed', id: '#1763' },
    ],
  },
  {
    key: '3',
    name: 'ZDOpen notice probe',
    template: 'zdopen_notice_contract@v0.9',
    group: 'prototype',
    area: 'Gov notice 🧾',
    status: 'failed',
    progress: 24,
    records: '860',
    lag: 'blocked',
    nextRun: '等待恢复',
    owner: 'amere-jess',
    avatar: 'AJ',
    comments: ['验证码风险升高，已触发降速和身份池切换。'],
    subIssues: [
      { title: '验证码风险熔断', status: 'failed', id: '#1771' },
      { title: '低速代理池验证', status: 'queued', id: '#1772' },
    ],
  },
  {
    key: '4',
    name: 'PDF document extract',
    template: 'pdf_document_extract@v1.3',
    group: 'beta',
    area: 'Documents 📄',
    status: 'queued',
    progress: 0,
    records: '0',
    lag: '-',
    nextRun: '18:30',
    owner: 'dareal-daryl',
    avatar: 'DD',
    comments: ['等待浏览器渲染池空闲后启动。'],
    subIssues: [
      { title: 'Docling fallback', status: 'queued', id: '#1781' },
      { title: '对象存储路径归档', status: 'queued', id: '#1782' },
    ],
  },
  {
    key: '5',
    name: 'Quality missing scan',
    template: 'quality_missing_scan@v1.1',
    group: 'beta',
    area: 'Quality ✅',
    status: 'paused',
    progress: 10,
    records: '1.1K',
    lag: 'manual',
    nextRun: '人工确认',
    owner: 'nova-blaster',
    avatar: 'NB',
    comments: ['abstract 缺失率超过 1%，等待字段合约复核。'],
    subIssues: [
      { title: '字段映射复核', status: 'paused', id: '#1791' },
      { title: '缺失样本回放', status: 'queued', id: '#1792' },
    ],
  },
  {
    key: '6',
    name: 'Market data launch backfill',
    template: 'market_data_contract@v1.0',
    group: 'launch',
    area: 'Market 🚀',
    status: 'running',
    progress: 33,
    records: '7.4K',
    lag: '1m 12s',
    nextRun: '持续运行',
    owner: 'exactly-myra',
    avatar: 'EM',
    comments: ['发布前回填任务，完成后会锁定模板版本。'],
    subIssues: [
      { title: '历史 URL 队列导入', status: 'completed', id: '#1801' },
      { title: 'RDS 写入校验', status: 'running', id: '#1802' },
    ],
  },
];
