import React, { useState } from 'react';
import ReactECharts from 'echarts-for-react';
import { Badge, Button, Card, Input, Progress, Segmented, Space, Table, Tabs, Tag, Typography } from 'antd';
import { PauseOutlined, ReloadOutlined, SearchOutlined, StopOutlined } from '@ant-design/icons';

const tasks = [
  { key: '1', name: 'Patent normalization', type: 'ETL', team: 'Data Operations', status: 'running', progress: 68, trigger: 'Pipeline', started: '10:24', duration: '12m 14s' },
  { key: '2', name: 'Template validation', type: 'AI', team: 'Research Lab', status: 'completed', progress: 100, trigger: 'Manual', started: '10:02', duration: '2m 36s' },
  { key: '3', name: 'Nightly data sync', type: 'Scheduler', team: 'Default Team', status: 'failed', progress: 42, trigger: 'Cron', started: '02:00', duration: '8m 09s' },
  { key: '4', name: 'Metadata indexing', type: 'System', team: 'Platform', status: 'queued', progress: 0, trigger: 'Event', started: '—', duration: '—' },
];

const UniversalTasks: React.FC = () => {
  const [selected, setSelected] = useState(tasks[0]);
  const graph = { backgroundColor: 'transparent', series: [{ type: 'graph', layout: 'force', roam: true, force: { repulsion: 170, edgeLength: 105 }, label: { show: true, color: '#E4E7EB', fontSize: 10, position: 'bottom' }, lineStyle: { color: '#018BFF', opacity: .55 }, edgeSymbol: ['none', 'arrow'], data: [{ name: 'ts_ods.patent', symbolSize: 36 }, { name: 'Patent ETL', symbolSize: 42 }, { name: selected.name, symbolSize: 52, itemStyle: { borderColor: '#018BFF', borderWidth: 3 } }, { name: 'ts_dwd.detail', symbolSize: 38 }], links: [{ source: 'ts_ods.patent', target: 'Patent ETL' }, { source: 'Patent ETL', target: selected.name }, { source: selected.name, target: 'ts_dwd.detail' }], itemStyle: { color: '#1A3248', borderColor: '#2DD4BF', borderWidth: 2 } }] };
  const status = (value: string) => <Badge status={value === 'running' ? 'processing' : value === 'completed' ? 'success' : value === 'failed' ? 'error' : 'default'} text={value} />;
  return <div className="graph-workspace"><header className="graph-page-header"><div><Typography.Text className="graph-kicker">PLATFORM-WIDE ORCHESTRATION</Typography.Text><Typography.Title level={2}>任务中心</Typography.Title><Typography.Text type="secondary">统一管理 ETL、AI、Pipeline、Scheduler 和 System 任务</Typography.Text></div><Space><Button icon={<ReloadOutlined />}>刷新</Button><Button type="primary">提交任务</Button></Space></header>
    <Card styles={{ body: { padding: 0 } }}><div style={{ padding: 14, display: 'flex', gap: 12, justifyContent: 'space-between' }}><Input prefix={<SearchOutlined />} placeholder="搜索任务、团队或资源" style={{ maxWidth: 360 }} /><Segmented options={['全部', 'ETL', 'AI', 'Pipeline', 'Scheduler', 'System']} /></div><Table size="small" pagination={false} dataSource={tasks} onRow={row => ({ onClick: () => setSelected(row), style: { cursor: 'pointer', background: selected.key === row.key ? 'rgba(1,139,255,.08)' : undefined } })} columns={[{ title: '任务', dataIndex: 'name' }, { title: '类型', dataIndex: 'type', render: v => <Tag>{v}</Tag> }, { title: '所属团队', dataIndex: 'team' }, { title: '状态', dataIndex: 'status', render: status }, { title: '进度', dataIndex: 'progress', width: 150, render: v => <Progress percent={v} size="small" status={v === 42 ? 'exception' : undefined} /> }, { title: '触发方式', dataIndex: 'trigger' }, { title: '开始时间', dataIndex: 'started' }, { title: '耗时', dataIndex: 'duration' }]} /></Card>
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(460px, 1.2fr) minmax(330px, .8fr)', gap: 16, marginTop: 16 }}><Card title="运行依赖" extra={status(selected.status)}><ReactECharts option={graph} style={{ height: 300 }} /></Card><Card title={selected.name} extra={<Space><Button size="small" icon={<PauseOutlined />}>暂停</Button><Button size="small" danger icon={<StopOutlined />}>取消</Button></Space>}><Tabs size="small" items={[{ key: 'timeline', label: '时间线', children: <div style={{ display: 'grid', gap: 14 }}><Badge status="success" text="任务已创建 · 10:24:02" /><Badge status="success" text="Worker 已领取 · 10:24:05" /><Badge status="processing" text="处理第 680 / 1000 批数据" /></div> }, { key: 'params', label: '参数', children: <pre style={{ color: '#94A3B8' }}>{JSON.stringify({ tenant: 'Acme Research', team: selected.team, retry: 3 }, null, 2)}</pre> }, { key: 'logs', label: '日志', children: <pre style={{ color: '#94A3B8', whiteSpace: 'pre-wrap' }}>[10:35:21] batch=680 processed=2500{`\n`}[10:35:22] checkpoint committed</pre> }]} /></Card></div>
  </div>;
};
export default UniversalTasks;
