import React, { useState } from 'react';
import { Avatar, Button, Checkbox, Form, Input, Radio, Select, Switch, Tag, Typography, message } from 'antd';
import { ApiOutlined, BellOutlined, CreditCardOutlined, DeleteOutlined, DownloadOutlined, EyeOutlined, GlobalOutlined, LinkOutlined, LockOutlined, MailOutlined, MoreOutlined, SafetyCertificateOutlined, SyncOutlined, UserOutlined } from '@ant-design/icons';
import './account-settings.css';
import './account-overrides.css';

type TabKey = 'account' | 'security' | 'billing' | 'notifications' | 'connections';

const tabs: Array<{ key: TabKey; label: string; icon: React.ReactNode }> = [
  { key: 'account', label: 'Account', icon: <UserOutlined /> },
  { key: 'security', label: 'Security', icon: <LockOutlined /> },
  { key: 'billing', label: 'Billing & Plans', icon: <CreditCardOutlined /> },
  { key: 'notifications', label: 'Notifications', icon: <BellOutlined /> },
  { key: 'connections', label: 'Connections', icon: <LinkOutlined /> },
];

const CardTitle = ({ title, description }: { title: string; description?: string }) => <div className="acc-card-title"><Typography.Title level={4}>{title}</Typography.Title>{description && <Typography.Text type="secondary">{description}</Typography.Text>}</div>;

const AccountSettings: React.FC = () => {
  const [tab, setTab] = useState<TabKey>('account');
  const [deactivate, setDeactivate] = useState(false);

  return <div className="acc-page">
    <nav className="acc-tabs" aria-label="Account settings sections">{tabs.map(item => <button type="button" key={item.key} className={tab === item.key ? 'is-active' : ''} onClick={() => setTab(item.key)}>{item.icon}<span>{item.label}</span></button>)}</nav>

    <div className="acc-content" key={tab}>
      {tab === 'account' && <>
        <section className="acc-card"><div className="acc-profile-head"><Avatar shape="square" size={100}>BG</Avatar><div><Button type="primary">Upload new photo</Button><Button>Reset</Button><Typography.Text type="secondary">Allowed JPG, GIF or PNG. Maximum size 800 KB.</Typography.Text></div></div>
          <Form layout="vertical" className="acc-form" initialValues={{ firstName: 'Blank', lastName: 'George', email: 'zhouy674896488@gmail.com', organization: 'Acme Research', phone: '', address: '', state: '', zip: '', country: 'China', language: 'English', timezone: 'Asia/Shanghai', currency: 'CNY' }} onFinish={() => message.success('Account changes saved')}>
            <div className="acc-form-grid"><Form.Item name="firstName" label="First name"><Input /></Form.Item><Form.Item name="lastName" label="Last name"><Input /></Form.Item><Form.Item name="email" label="Email"><Input /></Form.Item><Form.Item name="organization" label="Organization"><Input /></Form.Item><Form.Item name="phone" label="Phone number"><Input placeholder="Add a phone number" /></Form.Item><Form.Item name="address" label="Address"><Input /></Form.Item><Form.Item name="state" label="State / Province"><Input /></Form.Item><Form.Item name="zip" label="ZIP / Postal code"><Input /></Form.Item><Form.Item name="country" label="Country"><Select options={[{ value: 'China', label: 'China' }, { value: 'United States', label: 'United States' }]} /></Form.Item><Form.Item name="language" label="Language"><Select options={[{ value: 'English', label: 'English' }, { value: 'Chinese', label: 'Chinese' }]} /></Form.Item><Form.Item name="timezone" label="Timezone"><Select options={[{ value: 'Asia/Shanghai', label: 'Asia/Shanghai (GMT+8)' }]} /></Form.Item><Form.Item name="currency" label="Currency"><Select options={[{ value: 'CNY', label: 'CNY' }, { value: 'USD', label: 'USD' }]} /></Form.Item></div>
            <div className="acc-actions"><Button type="primary" htmlType="submit">Save changes</Button><Button htmlType="reset">Cancel</Button></div>
          </Form>
        </section>
        <section className="acc-card acc-danger"><CardTitle title="Deactivate account" /><div className="acc-danger-box"><strong>Are you sure you want to deactivate your account?</strong><span>Once deactivated, access to all Asiral Helio workspaces will be suspended.</span></div><Checkbox checked={deactivate} onChange={event => setDeactivate(event.target.checked)}>I confirm my account deactivation</Checkbox><div><Button danger type="primary" disabled={!deactivate}>Deactivate account</Button></div></section>
      </>}

      {tab === 'security' && <>
        <section className="acc-card acc-password-card"><CardTitle title="Change password" description="Use a strong password that you do not reuse elsewhere." /><Form layout="vertical" className="acc-form acc-password-form" onFinish={() => message.success('Password updated')}><div className="acc-form-grid"><Form.Item label="Current password" name="current" rules={[{ required: true }]}><Input.Password /></Form.Item><div /><Form.Item label="New password" name="password" rules={[{ required: true }, { min: 8 }]}><Input.Password /></Form.Item><Form.Item label="Confirm new password" name="confirm" dependencies={['password']} rules={[{ required: true }, ({ getFieldValue }) => ({ validator(_, value) { return !value || getFieldValue('password') === value ? Promise.resolve() : Promise.reject(new Error('Passwords do not match')); } })]}><Input.Password /></Form.Item></div><div className="acc-password-requirements"><strong>Password requirements:</strong><ul><li>Minimum 8 characters long — the more, the better</li><li>At least one lowercase and one uppercase character</li><li>At least one number, symbol, or whitespace character</li></ul></div><div className="acc-actions"><Button type="primary" htmlType="submit">Save changes</Button><Button>Cancel</Button></div></Form></section>
        <section className="acc-card"><CardTitle title="Two-step verification" description="Add an additional layer of security to your account." /><div className="acc-setting-line"><div className="acc-setting-icon"><SafetyCertificateOutlined /></div><div><strong>Authenticator verification</strong><span>Verification is required for new devices and sensitive operations.</span></div><Switch defaultChecked /></div></section>
        <section className="acc-card"><CardTitle title="API keys" description="Create and revoke keys used by platform integrations." /><div className="acc-api-key-list"><div className="acc-api-key-row"><div className="acc-setting-icon"><ApiOutlined /></div><div><strong>Production pipeline</strong><span>sk_live_••••••••9K4D · Created Aug 12, 2026 · Last used 4 min ago</span></div><span className="acc-api-status">Active</span><div className="acc-api-actions"><Button type="text" icon={<SyncOutlined />} title="Rotate key" aria-label="Rotate Production pipeline key" /><Button type="text" danger icon={<DeleteOutlined />} title="Revoke key" aria-label="Revoke Production pipeline key" /></div></div><div className="acc-api-key-row"><div className="acc-setting-icon"><ApiOutlined /></div><div><strong>Local development</strong><span>sk_test_••••••••2F8A · Created Jun 03, 2026 · Last used yesterday</span></div><span className="acc-api-status">Active</span><div className="acc-api-actions"><Button type="text" icon={<SyncOutlined />} title="Rotate key" aria-label="Rotate Local development key" /><Button type="text" danger icon={<DeleteOutlined />} title="Revoke key" aria-label="Revoke Local development key" /></div></div></div><Button type="primary" className="acc-create-key"><ApiOutlined /> Create API key</Button></section>
        <section className="acc-card"><CardTitle title="Recent devices" description="Review devices that recently accessed your workspace." /><div className="acc-device"><div className="acc-setting-icon"><GlobalOutlined /></div><div><strong>Windows · Chrome</strong><span>127.0.0.1 · Current session</span></div><span className="acc-device-status">Active now</span><Button type="text" className="acc-device-action">Details</Button></div><div className="acc-device"><div className="acc-setting-icon"><GlobalOutlined /></div><div><strong>Linux · API Client</strong><span>Acme Research · 2 hours ago</span></div><span className="acc-device-location">Shanghai, CN</span><Button size="small" danger className="acc-signout">Sign out</Button></div></section>
        <section className="acc-card"><CardTitle title="Security notifications" description="Choose which security events require your attention." /><div className="acc-setting-line"><div className="acc-setting-icon"><MailOutlined /></div><div><strong>Email security alerts</strong><span>Send alerts for password, MFA and new-device changes.</span></div><Switch defaultChecked /></div><div className="acc-setting-line"><div className="acc-setting-icon"><BellOutlined /></div><div><strong>Session expiry reminders</strong><span>Notify before an active session expires.</span></div><Switch defaultChecked /></div></section>
      </>}

      {tab === 'billing' && <>
        <section className="acc-card acc-current-plan"><CardTitle title="Current plan" /><div className="acc-current-plan-grid"><div className="acc-plan-summary"><div><strong>Your Current Plan is Enterprise</strong><span>Tenant-wide governance and advanced data operations</span></div><div><strong>Active until Sep 20, 2026</strong><span>We will send you a notification upon subscription expiration</span></div><div><div className="acc-plan-price"><strong>¥12,800 Per Month</strong><span>Popular</span></div><span>Standard plan for growing data teams and organizations</span></div></div><div className="acc-plan-cycle"><div className="acc-plan-alert"><strong>We need your attention!</strong><span>Your plan requires an update</span></div><div className="acc-plan-days"><span>Days</span><strong>12 of 30 Days</strong></div><div className="acc-plan-progress"><i style={{ width: '40%' }} /></div><span className="acc-plan-remaining">18 days remaining until your plan requires update</span></div></div><div className="acc-plan-buttons"><Button type="primary">Upgrade plan</Button><Button>Cancel subscription</Button></div></section>
        <section className="acc-card"><CardTitle title="Payment methods" /><div className="acc-payment-layout"><Form layout="vertical" className="acc-payment-form" onFinish={() => message.success('Payment method saved')}><Radio.Group defaultValue="card" className="acc-payment-types"><Radio value="card">Credit/Debit/ATM Card</Radio><Radio value="paypal">PayPal account</Radio></Radio.Group><Form.Item label="Card number" name="cardNumber"><Input placeholder="1356 3215 6548 7898" /></Form.Item><div className="acc-payment-fields"><Form.Item label="Name" name="cardName"><Input placeholder="John Doe" /></Form.Item><Form.Item label="Exp. date" name="expiry"><Input placeholder="MM/YY" /></Form.Item><Form.Item label="CVV code" name="cvv"><Input placeholder="654" maxLength={4} /></Form.Item></div><Checkbox defaultChecked>Save card for future billing?</Checkbox><div className="acc-payment-form-actions"><Button type="primary" htmlType="submit">Save changes</Button><Button htmlType="reset">Cancel</Button></div></Form><div className="acc-saved-cards"><Typography.Title level={5}>My Cards</Typography.Title><div className="acc-saved-card"><div className="acc-saved-card-content"><div className="acc-card-brand mastercard-brand"><img src="https://cdn.simpleicons.org/mastercard" alt="Mastercard" /></div><div className="acc-saved-details"><div className="acc-saved-name-row"><strong>Blank George</strong><Tag color="cyan">PRIMARY</Tag></div><span className="acc-card-number">•••• •••• •••• 4242</span></div><div className="acc-saved-side"><div className="acc-saved-actions"><Button>Edit</Button><Button danger>Delete</Button></div><span className="acc-card-expiry">Card expires at 12/28</span></div></div></div><div className="acc-saved-card"><div className="acc-saved-card-content"><div className="acc-card-brand visa-brand"><img src="https://cdn.simpleicons.org/visa" alt="Visa" /></div><div className="acc-saved-details"><div className="acc-saved-name-row"><strong>Acme Research</strong></div><span className="acc-card-number">•••• •••• •••• 8899</span></div><div className="acc-saved-side"><div className="acc-saved-actions"><Button>Edit</Button><Button danger>Delete</Button></div><span className="acc-card-expiry">Card expires at 04/27</span></div></div></div></div></div></section>
        <section className="acc-card"><CardTitle title="Billing details" /><div className="acc-billing-details"><div><span>Billing email</span><strong>zhouy674896488@gmail.com</strong></div><div><span>Billing address</span><strong>Acme Research · Shanghai, China</strong></div><Button>Update details</Button></div></section>
        <section className="acc-card"><CardTitle title="Plan usage" description="Current usage across your tenant allowance." /><div className="acc-usage"><div><span>Storage</span><strong>680 GB <em>of 1 TB</em></strong><i><b style={{ width: '68%' }} /></i></div><div><span>Monthly tasks</span><strong>8,420 <em>of 20,000</em></strong><i><b style={{ width: '42%' }} /></i></div><div><span>Team members</span><strong>24 <em>of 50</em></strong><i><b style={{ width: '48%' }} /></i></div></div></section>
        <section className="acc-card"><CardTitle title="Billing history" /><div className="acc-table"><div className="acc-table-head"><span>Invoice</span><span>Date</span><span>Amount</span><span>Status</span><span>Actions</span></div>{['INV-2026-008','INV-2026-007','INV-2026-006'].map((id, index) => <div className="acc-table-row" key={id}><strong>{id}</strong><span>{['Aug 20, 2026','Jul 20, 2026','Jun 20, 2026'][index]}</span><span>¥12,800</span><span className="acc-billing-status"><i /> Paid</span><div className="acc-table-actions"><Button type="text" icon={<EyeOutlined />} aria-label={`View ${id}`} /><Button type="text" icon={<DownloadOutlined />} aria-label={`Download ${id}`} /><Button type="text" icon={<MoreOutlined />} aria-label={`More actions for ${id}`} /></div></div>)}</div></section>
      </>}

      {tab === 'notifications' && <section className="acc-card acc-notifications-card"><div className="acc-notifications-intro"><Typography.Title level={4}>Recent Devices</Typography.Title><Typography.Text type="secondary">We need permission from your browser to show notifications. <button type="button">Request Permission</button></Typography.Text></div><div className="acc-notification-table" role="table" aria-label="Notification preferences"><div className="acc-notification-head" role="row"><span>Type</span><span>Email</span><span>Browser</span><span>App</span></div>{[{ title: 'New for you', email: true, browser: true, app: true }, { title: 'Account activity', email: true, browser: true, app: true }, { title: 'A new browser used to sign in', email: true, browser: true, app: false }, { title: 'A new device is linked', email: true, browser: false, app: false }].map(item => <div className="acc-notification-row" role="row" key={item.title}><span>{item.title}</span><Checkbox defaultChecked={item.email} aria-label={`${item.title} email`} /><Checkbox defaultChecked={item.browser} aria-label={`${item.title} browser`} /><Checkbox defaultChecked={item.app} aria-label={`${item.title} app`} /></div>)}</div><div className="acc-notifications-footer"><Form layout="vertical"><Form.Item label="When should we send you notifications?"><Select defaultValue="online" options={[{ value: 'online', label: "Only when I'm online" }, { value: 'anytime', label: 'Anytime' }]} /></Form.Item></Form><div className="acc-notification-actions"><Button type="primary" onClick={() => message.success('Notification preferences saved')}>Save changes</Button><Button>Discard</Button></div></div></section>}

      {tab === 'connections' && <div className="acc-connections-grid">
        <section className="acc-card"><CardTitle title="Connected Accounts" description="Display content from your connected accounts on your site" /><div className="acc-connection-list">{[
          ['google', 'Google', 'Calendar and contacts', true],
          ['slack', 'Slack', 'Communication', false],
          ['github', 'Github', 'Manage your Git repositories', true],
          ['mailchimp', 'Mailchimp', 'Email marketing service', true],
          ['asana', 'Asana', 'Communication', false],
        ].map(([brand, name, detail, enabled]) => <div className="acc-connection-item" key={String(brand)}><img src={`https://cdn.simpleicons.org/${brand}`} alt={`${name} logo`} /><div><strong>{name}</strong><span>{detail}</span></div><Switch defaultChecked={Boolean(enabled)} aria-label={`${name} connection`} /></div>)}</div></section>
        <section className="acc-card"><CardTitle title="Social Accounts" description="Display content from social accounts on your site" /><div className="acc-connection-list">{[
          ['facebook', 'Facebook', 'Not Connected', false],
          ['x', 'Twitter', '@AsiralHelio', true],
          ['instagram', 'Instagram', '@AsiralHelio', true],
          ['dribbble', 'Dribbble', 'Not Connected', false],
          ['behance', 'Behance', 'Not Connected', false],
        ].map(([brand, name, detail, connected]) => <div className="acc-connection-item" key={String(brand)}><img src={`https://cdn.simpleicons.org/${brand}`} alt={`${name} logo`} /><div><strong>{name}</strong><span className={connected ? 'is-connected' : ''}>{detail}</span></div><Button className="acc-social-action" type={connected ? 'primary' : 'default'} aria-label={`${connected ? 'Disconnect' : 'Connect'} ${name}`}>{connected ? <DeleteOutlined /> : <LinkOutlined />}</Button></div>)}</div></section>
      </div>}
    </div>
  </div>;
};

export default AccountSettings;
